package: download
version: '1.0.0-beta1'
author: FriendsOfREDAXO
supportpage: https://github.com/FriendsOfREDAXO/download

requires:
    packages:
        media_manager: '^2.0.0'
    redaxo: '^5.2.0'

pages:
    media_manager/download:
        title: translate:title
        perm: download[]
